FUZZY_MATCH_EXACT = 1.0
FUZZY_MATCH_PREFIX = 0.88
FUZZY_MATCH_SUBSTRING = 0.65

FUZZY_TABLE_THRESHOLD = 0.55

FUZZY_LEVENSHTEIN_FLOOR = 0.60


COL_CODE_LABEL_SUFFIX_CONFIDENCE = 0.92

COL_CODE_LABEL_ID_CONFIDENCE = 0.85

COL_CODE_LABEL_SEMANTIC_CONFIDENCE = 0.72

COL_NAME_PAIR_CONFIDENCE = 0.93

COL_PK_UNIQUENESS_RATIO = 0.95

COL_FK_CONFIDENCE = 0.82

COL_DIM_METRIC_CONFIDENCE = 0.80
COL_DIM_MAX_CARDINALITY = 75

COL_TEMPORAL_CONFIDENCE = 0.88

COOCCURRENCE_DECAY_FACTOR = 0.85
COOCCURRENCE_MIN_THRESHOLD = 2


KG_WEIGHT_BASE = 1.0
KG_WEIGHT_ID = 1.8
KG_WEIGHT_CURRENCY = 1.6
KG_WEIGHT_CATEGORICAL = 1.4

WORD_OVERLAP_WEIGHT = 7
CURRENCY_TAG_BOOST = 5
DISAMBIGUATION_FACT_BOOST = 10
DISAMBIGUATION_INDEX_BOOST = 7
INSURANCE_VALUE_INDEX_BOOST = 5
RATE_TABLE_BOOST = 7

MIN_CONCEPT_HITS = 3
MIN_CONCEPT_MATCH_SCORE = 4
MIN_COLUMN_SCORE = 0.15
MIN_VALUE_SCORE = 0.20
VALUE_FILTER_SCORE = 0.25
TABLE_SCORE_RATIO = 0.55
MIN_COL_PER_TABLE = 2
MIN_TABLE_SIZE_FOR_METRIC = 500

HAVING_MIN_USEFUL_DEFAULT = 5
HAVING_MIN_USEFUL_CROSS = 200
HAVING_MIN_RATE_THRESHOLD = 15

DEFAULT_BREAKDOWN_LIMIT = 25
DEFAULT_TREND_LIMIT = 48
DEFAULT_RANKING_LIMIT = 10
DEFAULT_LOOKUP_LIMIT = 100

MIN_SEMANTIC_CONFIDENCE = 0.40
CONFIDENCE_PENALTY_LOW_TFIDF = 0.20
CONFIDENCE_PENALTY_MISSING_REL = 0.12

ROW_COUNT_DIVISOR = 10000
ROW_BOOST_CAP = 1.8


FORECAST_HORIZON = 6
FORECAST_TEST_RATIO = 0.20
FORECAST_MIN_DATAPOINTS = 6

HW_ALPHA = 0.15
HW_BETA = 0.08
HW_GAMMA = 0.05
HW_MIN_SEASON = 4

ES_ALPHA_MIN = 0.05
ES_ALPHA_MAX = 0.95
ES_ALPHA_STEPS = 19

ARIMA_MAX_ORDER = 3

SEASONALITY_AUTOCORR_THRESHOLD = 0.25
SEASONALITY_LAG_OPTIONS = [4, 6, 12]

MC_SIMULATIONS = 1000

CONSENSUS_FAILED_WEIGHT = 0.05

MAX_INSIGHTS = 8


SCHEMA_CACHE_TTL_HOURS = 24.0
QUERY_CACHE_TTL_VOLATILE = 1.0
QUERY_CACHE_TTL_REFERENCE = 24.0
INTELLIGENCE_CACHE_TTL = 24.0

CACHE_FILLER_WORDS = frozenset({
    'what', 'is', 'the', 'show', 'me', 'give', 'find', 'get',
    'list', 'display', 'tell', 'how', 'many', 'which', 'are',
    'were', 'was', 'has', 'have', 'does', 'do', 'a', 'an', 'of',
    'for', 'in', 'by', 'to', 'from', 'with', 'each', 'every',
    'all', 'please', 'can', 'you', 'i', 'want', 'need', 'would',
    'like', 'could',
})


KPI_MIN_FREQUENCY = 3
KPI_MIN_USERS = 2
TRENDING_WINDOW_DAYS = 7
TRENDING_MIN_INCREASE_PCT = 50
PEER_SUGGESTION_MIN_COOCCUR = 2
MAX_SUGGESTIONS_PER_CATEGORY = 6
QUERY_RETENTION_DAYS = 90


MEMORY_STABILITY_ACCESS_WEIGHT = 0.25
MEMORY_STABILITY_IMPORTANCE_BASE = 0.5
MEMORY_STRENGTH_CAP = 4.0
MEMORY_IMPORTANCE_EMA_OLD = 0.75
MEMORY_IMPORTANCE_EMA_NEW = 0.25

STABILITY_GAIN_EASY = 0.08
STABILITY_GAIN_OPTIMAL = 0.25
STABILITY_GAIN_HARD = 0.40
STABILITY_GAIN_FORGOTTEN = 0.15

FORGET_THRESHOLD = 0.08
STM_RECALL_THRESHOLD = 0.35
LTM_RECALL_THRESHOLD = 0.15

WORKING_MEMORY_CAPACITY = 7
WORKING_MEMORY_HALFLIFE = 300.0
STM_CAPACITY = 80

CONSOLIDATION_MIN_ACCESS = 2
CONSOLIDATION_MIN_IMPORTANCE = 0.65


TFIDF_MIN_SEARCH_SCORE = 0.08
TFIDF_IDF_SMOOTHING = 1.0
TFIDF_SUBLINEAR_TF = True


SEMANTIC_CACHE_SIZE = 500
SEMANTIC_CACHE_SIMILARITY = 0.88

FEEDBACK_SUCCESS = 1.0
FEEDBACK_PARTIAL = 0.5
FEEDBACK_FAILURE = 0.2

HOPFIELD_RECALL_THRESHOLD = 0.82


VALUE_DISCOVERY_MAX_CARDINALITY = 80
VALUE_DISCOVERY_MIN_TERM_LEN = 2
VALUE_DISCOVERY_SHORT_TERM_SKIP = 3
KNOWN_SHORT_CODES = frozenset({
    'icd', 'cpt', 'ndc', 'drg', 'hcc', 'snf', 'icu', 'adt',
    'pos', 'tos', 'rev', 'cms', 'kpi', 'snp', 'ppo', 'hmo',
    'ehr', 'emr', 'phi', 'pha', 'rx', 'dx', 'px', 'ed', 'er',
    'ip', 'op', 'ob', 'or', 'icu', 'npi',
})
